import {loading} from "./modules/loading";
import {applyPicturefill} from "./modules/picturefill";
import {fadeIn} from "./modules/fadein";
import {accordion} from "./modules/accordion";
import {smoothScroll} from "./modules/smoothscroll";
import {tabSwitch} from "./modules/tabswitch";
import {modal} from "./modules/modal";
import {scrollTop} from "./modules/scrolltop";
import {adjustViewport} from "./modules/adjustViewport";
import mySwiper from "./modules/mySwiper";

loading();
applyPicturefill();
fadeIn();
accordion();
smoothScroll();
tabSwitch();
modal();
scrollTop();
adjustViewport();
mySwier();